{
 "title": "ran slicing flexric gym",
 "time": { "from": "2024-01-10T00:51:33.867Z", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "power head room",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "phr", "legendFormat": "imsi={{imsi}}" }
   ]
  },
  {
   "title": "MAC Uplink SDU Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 0 },
   "targets": [
    { "expr": "ul_aggr_sdus", "legendFormat": "imsi={{imsi}}" }
   ]
  },
  {
   "title": "Uplink Throughput (based on tbs)",
   "type": "timeseries",
   "description": "avg over 10 sec",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    { "expr": "rate(ul_aggr_tbs[10s])", "legendFormat": "imsi={{imsi}}" }
   ]
  },
  {
   "title": "Channel Quality indicator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "targets": [
    { "expr": "wb_cqi", "legendFormat": "imsi={{imsi}}" }
   ]
  },
  {
   "title": "MAC Downlink SDU Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 8 },
   "targets": [
    { "expr": "dl_aggr_sdus", "legendFormat": "ismi={{imsi}}" }
   ]
  },
  {
   "title": "Downlink Throughput (based on tbs)",
   "type": "timeseries",
   "description": "avg over 10 seconds",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "rate(dl_aggr_tbs[10s])", "legendFormat": "imsi={{imsi}}" }
   ]
  },
  {
   "title": "PDCP Transmitted PDU Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "txpdu_pkts", "legendFormat": "imsi={{imsi}}" }
   ]
  },
  {
   "title": "PDCP Received PDU Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "rxpdu_pkts", "legendFormat": "imsi={{imsi}}" }
   ]
  },
  {
   "title": "PDCP Transmitted PDU Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "txpdu_bytes", "legendFormat": "imsi={{imsi}}" }
   ]
  },
  {
   "title": "PDCP Received PDU Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    { "expr": "rxpdu_bytes", "legendFormat": "imsi={{imsi}}" }
   ]
  },
  { "title": "Panel Title", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 } }
 ]
}