{
 "title": "Slice Dashboard",
 "time": { "from": "now-8h", "to": "now-4h" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Slice Downlink Average Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "slice_dl_throughput", "legendFormat": "slice_id={{slice_id}}" }
   ]
  },
  {
   "title": "Slice Active User Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "slice_active_users", "legendFormat": "slice_id={{slice_id}}" }
   ]
  },
  {
   "title": "Slice Power Headroom",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "slice_phr", "legendFormat": "slice_id={{slice_id}}" }
   ]
  },
  {
   "title": "Slice Average Channel Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "slice_cqi", "legendFormat": "slice_id={{slice_id}}" }
   ]
  }
 ]
}